use_frameworks!

platform :ios, '8.0'

target 'LSWTreeView_Example' do
  pod 'LSWTreeView', :path => '../'

  target 'LSWTreeView_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
